### ISSUE TITLE
Guns dont fire.

### ISSUE THREAD

**Issue by randoomx8** [rav3dev/vrtwix#7]
When I attempt to fire a gun, the following message appears:
```cs
NullReferenceException: Object reference not set to an instance of an object
Magazine.SortingBulletInMagazine () (at Assets/_VRtwix/Scripts/Interactables/Magazine.cs:73)
Magazine.GetBullet () (at Assets/_VRtwix/Scripts/Interactables/Magazine.cs:147)
PrimitiveWeapon.LoadBullet () (at Assets/_VRtwix/Scripts/Interactables/PrimitiveWeapon.cs:68)
UnityEngine.Events.InvokableCall.Invoke () (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <94c5f4c38cdc42d2b006f8badef04394>:0)
ManualReload.FixedUpdate () (at Assets/_VRtwix/Scripts/Interactables/ManualReload.cs:81)
```

Renaming `Bullet_12` to `Bullet` removes the error from the logs but still wont allow guns to fire.
I have been tweaking stuff such as enabling "active" and messing with other components but I really cant figure it out.

**I asked around and this appears to be a consistent issue across all users.**
_Ps, it appears you guys are using Polygon files (the shaders folder for example) without the correct licence, I suggest it is replaced with a legal alternative._

**Comment by Oyshoboy** [comment]
Thanks for report, will look into

**Comment by Oyshoboy** [comment]
Sorry for late answer, I think I found the problem.
You need to assign new actions **"Trigger" ( type: vector1 )** and **"TriggerClick" ( type: boolean )** by:
**`Window => SteamVR Input => add actions`**

And then setup bindings:
**`Open Binging UI" => Current Binding => Trigger => Add ( Click - triggerclick, Pull - trigger )`**

![f1vXam9](https://user-images.githubusercontent.com/23486183/83937716-0fc03d80-a784-11ea-94b5-08293b2b38d0.png)

Please verify if that's gonna help ( will add it to readme ).

About synty studios shader thanks for suggestion, will replace next commit!
